- name: Install Node.js and Yarn
  become: yes
  apt:
    name:
      - nodejs
      - yarn
    state: latest


- name: Create frontend directory
  become: yes
  file:
    path: "/data/wordpress/frontend"
    state: directory
    mode: 0755

- name: Copy React files to frontend directory
  become: yes
  copy:
    src: ../FrontEnd
    dest: /data/wordpress/frontend

- name: Install frontend dependencies
  become: yes
  shell: yarn
  args:
    chdir: /data/wordpress/frontend/FrontEnd


- name: Build frontend
  become: yes
  shell: yarn start
  args:
    chdir: /data/wordpress/frontend/FrontEnd

- name: Copy built files to WordPress container
  become: yes
  copy:
    src: /data/wordpress/frontend/FrontEnd/build
    dest: /var/www/html

- name: Restart WordPress
  become: yes
  shell: docker-compose restart wordpress
  args:
    chdir: /data/wordpress
