- name: Create frontend directory
  become: yes
  file:
    path: "/data/wordpress/frontend"
    state: directory
    mode: 0755

- name: Copy React files to frontend directory
  become: yes
  copy:
    src: ../FrontEnd
    dest: /data/wordpress/frontend

- name: Install frontend dependencies
  become: yes
  shell: yarn
  args:
    chdir: /data/wordpress/frontend/FrontEnd

- name: Build frontend
  become: yes
  shell: yarn start &
  args:
    chdir: /data/wordpress/frontend/FrontEnd


- name: Start server
  become: yes
  shell: docker-compose up -d --build
  args:
    chdir: /data/wordpress
