couchdb_image: ibmcom/couchdb3:latest
couchdb_user: admin
couchdb_pass: admin
couchdb_VERSION: '3.2.1'
couchdb_cookie: 'a192aeb9904e6590849337933b000c99'
couchdb_container_name: b53d45e6ef2b
couchdb_port: 5984