- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /data/CouchDB
#
- name: Start server
  become:
    yes
  shell: docker-compose up  --build -d
  args:
    chdir: /data/CouchDB