---
- name: Create Wordpress directory
  become: true
  ansible.builtin.file:
    path: "{{ wp_dir }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true
    state: directory

- name: Configure compose
  become: true
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ wp_dir }}/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"