---
- name: Create Wordpress directory
  become: true
  ansible.builtin.file:
    path: "/data/wordpress"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: true
    state: directory

- name: Configure compose
  become: true
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: "/data/wordpress/docker-compose.yaml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
