- name: Copy frontend files to WordPress container
  become: yes
  copy:
    src: ../Backend
    dest: /data/wordpress

- name: Restart WordPress
  become: yes
  shell: docker-compose restart wordpress
  args:
    chdir: /data/wordpress
    
- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /data/wordpress

- name: Start server
  become: yes
  shell: docker-compose up -d --build
  args:
    chdir: /data/wordpress