- name: generate frontend configuration of backend
  become:
    yes
  template:
    src: ../FrontEnd/craco.config.js
    dest: /data/wordpress/config/webpackDevServer.config.js

- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /data/wordpress

- name: Start server
  become: yes
  shell: docker-compose up -d --build
  args:
    chdir: /data/wordpress