---
# Show all available Openstack images (just for demo, you don't need this task to create instance) 
- name: Retrieve all available Openstack images
  openstack.cloud.image_info:
  register: image_result

- name: Show images
  ansible.builtin.debug:
    msg: "{{ image_result.image }}"
