- hosts: localhost
  vars_files:
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: set-tek
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group

- hosts: all
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/couchdb.yaml
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: tek.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: install-dependencies
    - role: setup_couchdb
