- hosts: couchdb
  vars_files:
    - host_vars/nectar.yaml
    - host_vars/couchdb.yaml
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: tek.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  gather_facts: true
  roles:
    - role: setup_couchdb
    
- hosts: masternode
  vars_files:
    - host_vars/couchdb.yaml
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: tek.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  gather_facts: true
  roles:
    - role: deploy-couchdb