---
- hosts: backend
  gather_facts: true
  vars_files:
    - host_vars/wordpress.yaml
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: tek.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: deploy-backend
    