---
- hosts: frontend
  gather_facts: true
  vars:
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: tek.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  roles:
    - role: start-frontend